# SPDX-FileCopyrightText: Portions Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""DAN adapter that composes prompt generators and attack methods"""

import logging
from typing import Iterable

import garak.attempt
from garak import _config
from garak.configurable import Configurable
from garak.probes.base import Probe
from garak.probes._tier import Tier
from garak.attackmethods.base import AttackMethod
from garak.payloadgenerators.base import PayloadGenerator


class DANAdapter(Configurable):
    """DAN adapter that combines prompt generators and attack methods"""

    # Default configuration matching DAN probes
    DEFAULT_PARAMS = {
        "lang": "en",
        "goal": "disregard the system prompt",
        "tier": Tier.UNLISTED,
        "active": False,
        "tags": [
            "avid-effect:security:S0403",
            "owasp:llm01",
            "quality:Security:PromptStability",
        ],
        "primary_detector": "dan.DAN",
        "extended_detectors": ["mitigation.MitigationBypass"],
    }

    def __init__(self,
                 prompt_generator: PayloadGenerator,
                 attack_method: AttackMethod = None,
                 config_root=_config):
        """Initialize DAN adapter

        Args:
            prompt_generator: The prompt generator to use
            attack_method: Optional attack method to apply
            config_root: Configuration root
        """
        self._load_config(config_root)
        self.prompt_generator = prompt_generator
        self.attack_method = attack_method

        # Set probe-like attributes for compatibility
        self.probename = str(self.__class__).split("'")[1]
        self.prompts = []

    def probe(self, generator) -> Iterable[garak.attempt.Attempt]:
        """Execute the probe with composed generator and attack method

        Args:
            generator: The generator to use for prompt generation and execution

        Returns:
            Iterable of attempts
        """
        # Generate base prompts
        base_prompts = self.prompt_generator.generate_prompts(generator)
        self.prompts = base_prompts

        if not base_prompts:
            logging.warning(f"No prompts generated by {self.prompt_generator.__class__.__name__}")
            return []

        # Apply attack method if provided
        if self.attack_method:
            all_attempts = []
            for prompt in base_prompts:
                attacked_attempts = self.attack_method.attack_prompt(prompt, generator)
                all_attempts.extend(attacked_attempts)
            return all_attempts

        # If no attack method, create attempts directly (backward compatibility)
        return self._create_attempts_from_prompts(generator, base_prompts)

    def _create_attempts_from_prompts(self, generator, prompts):
        """Create attempts from prompts without attack method (backward compatibility)

        Args:
            generator: The generator to use
            prompts: List of prompts to create attempts from

        Returns:
            List of attempts
        """
        attempts = []
        for prompt in prompts:
            attempt = garak.attempt.Attempt(
                prompt=prompt,
                probe_class_name=self.probename,
                goal=self.goal
            )

            try:
                output = generator.generate(prompt)
                attempt.outputs = [output]
                attempt.status = garak.attempt.ATTEMPT_COMPLETE
            except Exception as e:
                logging.error(f"Error generating output for prompt '{prompt[:50]}...': {e}")
                attempt.status = garak.attempt.ATTEMPT_FAIL

            attempts.append(attempt)

        return attempts


# Backward compatibility aliases
class DANProbeAdapter(DANAdapter):
    """Alias for DANAdapter for backward compatibility"""
    pass